# Generated by Django 5.0.6 on 2024-06-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEntreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entrenamiento', models.IntegerField(help_text='Tipo Entrenamiento')),
                ('Valor', models.FloatField()),
                ('DuracionDias', models.IntegerField(help_text='Duración en días')),
                ('Objetivo', models.CharField(max_length=100)),
            ],
        ),
    ]
